# Generated by Django 5.0.6 on 2024-09-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_register_contact_alter_register_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='register',
            name='unique_email_hospital',
        ),
    ]
